import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:todo_app/utils/importance_enum.dart';

import '../../constants/app_paths.dart';
import '../data/local/task_hive.dart';
import '../data/remote/element_response.dart';

part 'task_model.freezed.dart'; // Associates our class with the code generated by Freezed
part 'task_model.g.dart'; // Makes class serializable

@freezed
class TaskModel with _$TaskModel {
  factory TaskModel({
    @JsonKey(name: 'id') required String id,
    @JsonKey(name: 'done') required bool isDone,
    @JsonKey(name: 'text') required String title,
    @JsonKey(name: 'importance') required Importance importance,
    @JsonKey(name: 'created_at') required int createdAt,
    @JsonKey(name: 'changed_at') required int changedAt,
    @JsonKey(name: 'last_updated_by') required String lastUpdatedBy,
    @JsonKey(name: 'deadline') int? deadlineTime,
    @JsonKey(name: 'color') String? color,
  }) = _TaskModel;

  factory TaskModel.fromJson(Map<String, Object?> json) =>
      _$TaskModelFromJson(json);

  factory TaskModel.fromHive(TaskHive task) {
    return TaskModel(
      id: task.id,
      isDone: task.isDone,
      title: task.title,
      importance: Importance.fromString(task.importance),
      createdAt: task.createdAt,
      changedAt: task.changedAt,
      lastUpdatedBy: task.lastUpdatedBy,
      deadlineTime: task.deadlineTime,
      color: task.color,
    );
  }

  factory TaskModel.fromResponse(ElementResponse task) {
    return TaskModel(
      id: task.id,
      isDone: task.isDone,
      title: task.title,
      importance: Importance.fromString(task.importance),
      createdAt: task.createdAt,
      changedAt: task.changedAt,
      lastUpdatedBy: task.lastUpdatedBy,
      deadlineTime: task.deadlineTime,
      color: task.color,
    );
  }
}

extension TaskModelExtesion on TaskModel {
  String? get prefixPath {
    if (!isDone && importance == Importance.important) {
      return AppPaths.prefixImportnantPriority.path;
    }

    if (!isDone && importance == Importance.low) {
      return AppPaths.prefixLowPriority.path;
    }

    return null;
  }

  String get checkboxPath {
    if (isDone) {
      return AppPaths.checked.path;
    } else if (importance == Importance.important) {
      return AppPaths.uncheckedImportant.path;
    }

    return AppPaths.unchecked.path;
  }
}
