import 'package:freezed_annotation/freezed_annotation.dart';

import 'domain/task_model.dart';

part 'tasks_request.freezed.dart'; // Associates our class with the code generated by Freezed
part 'tasks_request.g.dart'; // Makes TasksRequest serializable

@freezed
class TasksRequest with _$TasksRequest {
  factory TasksRequest({
    @JsonKey(name: 'list') required List<TaskModel> tasks,
  }) = _TasksRequest;

  factory TasksRequest.fromJson(Map<String, Object?> json) =>
      _$TasksRequestFromJson(json);

  factory TasksRequest.fromModels(List<TaskModel> tasks) =>
      TasksRequest(tasks: tasks);
}
