// ignore_for_file: invalid_annotation_target

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:todo_app/models/task_element.dart';

part 'task.freezed.dart'; // Associates our `main.dart` with the code generated by Freezed
part 'task.g.dart'; // Makes TaskResponse serializable

@freezed
class Task with _$Task {
  factory Task({
    @JsonKey(name: 'status') required String status,
    @JsonKey(name: 'element') required TaskElement task,
    @JsonKey(name: 'revision') required int revision,
  }) = _Task;

  factory Task.fromJson(Map<String, Object?> json) => _$TaskFromJson(json);
}
