// ignore_for_file: invalid_annotation_target

import 'package:freezed_annotation/freezed_annotation.dart';

part 'task_element_response.freezed.dart'; // Associates our `main.dart` with the code generated by Freezed
part 'task_element_response.g.dart'; // Makes TaskResponse serializable

@freezed
class TaskElementResponse with _$TaskElementResponse {
  factory TaskElementResponse({
    required String id,
    @JsonKey(name: 'done') required bool isDone,
    @JsonKey(name: 'text') required String title,
    @JsonKey(name: 'importance') required String priority,
    @JsonKey(name: 'created_at') required int createdAt,
    @JsonKey(name: 'changed_at') required int changedAt,
    @JsonKey(name: 'last_updated_by') required String lastUpdatedBy,
    @JsonKey(name: 'deadline') int? deadlineTime,
    @JsonKey(name: 'color') String? color,
  }) = _TaskElementResponse;

  factory TaskElementResponse.fromJson(Map<String, Object?> json) =>
      _$TaskElementResponseFromJson(json);
}
