// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPjEsnNKl18wyV3PI726GxHKm6aZjJ9KI',
    appId: '1:488280424830:web:d303aacf888e7f527cb32f',
    messagingSenderId: '488280424830',
    projectId: 'todo-app-d9ac5',
    authDomain: 'todo-app-d9ac5.firebaseapp.com',
    storageBucket: 'todo-app-d9ac5.appspot.com',
    measurementId: 'G-0CF2LT1RKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_gXHGLevNZ8lyGotXxw0_OvpSMJkQ3No',
    appId: '1:488280424830:android:732e8d6d693939377cb32f',
    messagingSenderId: '488280424830',
    projectId: 'todo-app-d9ac5',
    storageBucket: 'todo-app-d9ac5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYCjNAOuRrqY6WEaI2Gc7dPIuZQg7Wxq8',
    appId: '1:488280424830:ios:a62834d29a9d10237cb32f',
    messagingSenderId: '488280424830',
    projectId: 'todo-app-d9ac5',
    storageBucket: 'todo-app-d9ac5.appspot.com',
    iosClientId:
        '488280424830-t71sn9irhkngfnj7tdqo71gedbc55cqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYCjNAOuRrqY6WEaI2Gc7dPIuZQg7Wxq8',
    appId: '1:488280424830:ios:a62834d29a9d10237cb32f',
    messagingSenderId: '488280424830',
    projectId: 'todo-app-d9ac5',
    storageBucket: 'todo-app-d9ac5.appspot.com',
    iosClientId:
        '488280424830-t71sn9irhkngfnj7tdqo71gedbc55cqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
