import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:todo_app/models/data/remote/element_response.dart';

import '../../domain/task_model.dart';

part 'task_response.freezed.dart'; // Associates our class with the code generated by Freezed
part 'task_response.g.dart'; // Makes class serializable

@freezed
class TaskResponse with _$TaskResponse {
  factory TaskResponse({
    @JsonKey(name: 'status') required String status,
    @JsonKey(name: 'element') required ElementResponse task,
    @JsonKey(name: 'revision') required int revision,
  }) = _TaskResponse;

  factory TaskResponse.fromJson(Map<String, Object?> json) =>
      _$TaskResponseFromJson(json);

  factory TaskResponse.fromModel(TaskModel task) {
    return TaskResponse(
      status: '200',
      task: ElementResponse.fromModel(task),
      revision: 0,
    );
  }
}
